BikeSettings2/Models/Bike.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BikeSettings2.Models
{
    public class Bike
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Manufacturer { get; set; }
        [Required]
        public string Model { get; set; }
        [DisplayName("Front Tyre PSI")]
        public int FrontTyrePSI { get; set; }
        [DisplayName("Rear Tyre PSI")]
        public int RearTyrePSI { get; set; }
        [DisplayName("Fork PSI")]
        public int ForkPSI { get; set; }
        [DisplayName("Fork Rebound")]
        public int ForkRebound { get; set; }
        [DisplayName("Shock PSI")]
        public int? ShockPSI { get; set; }
        [DisplayName("Shock Rebound")]
        public int? ShockRebound { get; set; }
        [NotMapped]
        public IFormFile? Image { get; set; }
    }
}

BikeSettings2/Controllers/BikeController.cs
using BikeSettings2.Data;
using BikeSettings2.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;

namespace BikeSettings2.Controllers
{
    public class BikeController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostingEnv;

        public BikeController(ApplicationDbContext db, IWebHostEnvironment hostingEnv)
        {
            _db = db;
            _hostingEnv = hostingEnv;
        }

        public IActionResult Index()
        {
            IEnumerable<Bike> objBikeList = _db.Bikes;
            return View(objBikeList);
        }

        //get
        public IActionResult Create()
        {

            return View();
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Bike obj)
        {
            if (obj.FrontTyrePSI < 1 || obj.FrontTyrePSI > 150)
            {
                ModelState.AddModelError("FrontTyrePSI", "PSI must be greater than 0 and less than 150");
            }
            if (obj.RearTyrePSI < 1 || obj.RearTyrePSI > 150)
            {
                ModelState.AddModelError("RearTyrePSI", "PSI must be greater than 0 and less than 150");
            }
            if (obj.ForkPSI < 1)
            {
                ModelState.AddModelError("ForkPSI", "PSI must be greater than 0");
            }
            if (obj.ForkRebound < 1)
            {
                ModelState.AddModelError("ForkRebound", "Rebound setting must be greater than 0");
            }
            if (obj.ShockRebound != null && obj.ShockRebound < 1)
            {
                ModelState.AddModelError("ShockRebound", "Rebound setting must be greater than 0 (leave blank for hardtails");
            }
            if (obj.ShockPSI != null && obj.ShockPSI < 1)
            {
                ModelState.AddModelError("ShockPSI", "PSI must be greater than 0 (leave blank for hardtails");
            }
            if (ModelState.IsValid)
            {
                _db.Bikes.Add(obj);
                _db.SaveChanges();

                string uploads = Path.Combine(_hostingEnv.WebRootPath, "Bikes/Images");

                var file = obj.Image;

                if (file != null && file.Length > 0)
                {
                    string filePath = Path.Combine(uploads, $"{obj.Id}.jpg");
                    using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                }

                return RedirectToAction("Index");
            }
            return View(obj);

        }
        //get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var bikeFromDb = _db.Bikes.Find(id);

            if (bikeFromDb == null)
            {
                return NotFound();
            }
            return View(bikeFromDb);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Bike obj)
        {
            if (obj.FrontTyrePSI < 1 || obj.FrontTyrePSI > 150)
            {
                ModelState.AddModelError("FrontTyrePSI", "PSI must be greater than 0 and less than 150");
            }
            if (obj.RearTyrePSI < 1 || obj.RearTyrePSI > 150)
            {
                ModelState.AddModelError("RearTyrePSI", "PSI must be greater than 0 and less than 150");
            }
            if (obj.ForkPSI < 1)
            {
                ModelState.AddModelError("ForkPSI", "PSI must be greater than 0");
            }
            if (obj.ForkRebound < 1)
            {
                ModelState.AddModelError("ForkRebound", "Rebound setting must be greater than 0");
            }
            if (obj.ShockRebound != null && obj.ShockRebound < 1)
            {
                ModelState.AddModelError("ShockRebound", "Rebound setting must be greater than 0 (leave blank for hardtails");
            }
            if (obj.ShockPSI != null && obj.ShockPSI < 1)
            {
                ModelState.AddModelError("ShockPSI", "PSI must be greater than 0 (leave blank for hardtails");
            }
            if (ModelState.IsValid)
            {
                _db.Bikes.Update(obj);
                _db.SaveChanges();

                if (obj.Image != null)
                {
                    if (System.IO.File.Exists(Path.Combine(_hostingEnv.WebRootPath, $"Bikes/Images/{obj.Id}.jpg")))
                    {
                        System.IO.File.Delete(Path.Combine(_hostingEnv.WebRootPath, $"Bikes/Images/{obj.Id}.jpg"));
                    }

                    string uploads = Path.Combine(_hostingEnv.WebRootPath, "Bikes/Images");

                    var file = obj.Image;

                    if (file != null && file.Length > 0)
                    {
                        string filePath = Path.Combine(uploads, $"{obj.Id}.jpg");
                        using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                    }

                }

                

                return RedirectToAction("Index");
            }
            return View(obj);

        }

        //get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var bikeFromDb = _db.Bikes.Find(id);

            if (bikeFromDb == null)
            {
                return NotFound();
            }
            return View(bikeFromDb);
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Bike obj)
        {
            if (obj == null)
            {
                return NotFound();
            }

            _db.Bikes.Remove(obj);
            _db.SaveChanges();

            if (System.IO.File.Exists(Path.Combine(_hostingEnv.WebRootPath, $"Bikes/Images/{obj.Id}.jpg")))
            {
                System.IO.File.Delete(Path.Combine(_hostingEnv.WebRootPath, $"Bikes/Images/{obj.Id}.jpg"));
            }
            return RedirectToAction("Index");
        }

        //get
        public IActionResult Search()
        {
            return View("Search");
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Search(string SearchPhrase)
        {
            SearchPhrase = SearchPhrase.Trim();
            return View("Index", _db.Bikes.Where(j => j.Manufacturer.Contains(SearchPhrase) || j.Model.Contains(SearchPhrase)));

        }

        //get
        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var bikeFromDb = _db.Bikes.Find(id);

            if (bikeFromDb == null)
            {
                return NotFound();
            }
            return View(bikeFromDb);
        }
    }


}

BikeSettings2/Views/Bike/Create.cshtml
@model Bike
@{
    ViewData["Title"] = "Index";
}

<form enctype="multipart/form-data" method="post">
    <div class="border rounded pt-3 mt-4 mx-auto">
        <div class="row pb-2 mx-auto">
            <h3 class="">Create a new Bike</h3>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Manufacturer"></label>
            <input asp-for="Manufacturer" class="form-control"/>
            <span asp-validation-for="Manufacturer" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Model"></label>
            <input asp-for="Model" class="form-control"/>
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="FrontTyrePSI"></label>
            <input asp-for="FrontTyrePSI" class="form-control"/>
            <span asp-validation-for="FrontTyrePSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="RearTyrePSI"></label>
            <input asp-for="RearTyrePSI" class="form-control"/>
            <span asp-validation-for="RearTyrePSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ForkPSI"></label>
            <input asp-for="ForkPSI" class="form-control"/>
            <span asp-validation-for="ForkPSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ForkRebound"></label>
            <input asp-for="ForkRebound" class="form-control"/>
            <span asp-validation-for="ForkRebound" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ShockPSI"></label>
            <input asp-for="ShockPSI" class="form-control"/>
            <span asp-validation-for="ShockPSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ShockRebound"></label>
            <input asp-for="ShockRebound" class="form-control"/>
            <span asp-validation-for="ShockRebound" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Image"></label>
            <input asp-for="Image" type="file"/>
  
        </div>
        <div class="mb-3 px-2 mx-auto">
            <button type="submit" class="btn btn-primary"> <i class="bi bi-bicycle"></i> &nbsp; Create Bike</button>
            <a asp-controller="Bike" asp-action="Index" class="btn btn-secondary">Back to List</a> 
        </div>
        
    </div>
</form>

@section Scripts{
        @{
            <partial name="_ValidationScriptsPartial" />
        }
}

BikeSettings2/Views/Bike/Delete.cshtml
@model Bike
@{
    ViewData["Title"] = "Index";
}

<form method="post"> 
    <div class="border rounded pt-3 mt-4 mx-auto">
        <div class="row pb-2 mx-auto">
            <h3 class="">Are you sure you want to delete?</h3>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Manufacturer"></label>
            <input asp-for="Manufacturer" class="form-control" disabled/>
            <span asp-validation-for="Manufacturer" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Model"></label>
            <input asp-for="Model" class="form-control" disabled/>
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="FrontTyrePSI"></label>
            <input asp-for="FrontTyrePSI" class="form-control" disabled/>
            <span asp-validation-for="FrontTyrePSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="RearTyrePSI"></label>
            <input asp-for="RearTyrePSI" class="form-control" disabled/>
            <span asp-validation-for="RearTyrePSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ForkPSI"></label>
            <input asp-for="ForkPSI" class="form-control" disabled/>
            <span asp-validation-for="ForkPSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ForkRebound"></label>
            <input asp-for="ForkRebound" class="form-control" disabled/>
            <span asp-validation-for="ForkRebound" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ShockPSI"></label>
            <input asp-for="ShockPSI" class="form-control" disabled/>
            <span asp-validation-for="ShockPSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ShockRebound"></label>
            <input asp-for="ShockRebound" class="form-control" disabled/>
            <span asp-validation-for="ShockRebound" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <button type="submit" class="btn btn-primary"> <i class="bi bi-trash"></i> &nbsp; Delete</button>
            <a asp-controller="Bike" asp-action="Index" method="post" class="btn btn-secondary">Back to List</a> 
        </div>

    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

BikeSettings2/Views/Bike/Details.cshtml
@model Bike
@{
    ViewData["Title"] = "Index";
}
<br />
<br />
<div class="container">
    <h2>Details</h2>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <table class="table table-bordered table-striped" style="width:50%">
                <thead>
                    <tr>
                        <th>
                            Attribute
                        </th>
                        <th>
                            Info
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Manufacturer
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.Manufacturer)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Model
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.Model)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Front Tyre PSI
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.FrontTyrePSI)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Rear Tyre PSI
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.RearTyrePSI)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Fork PSI
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.ForkPSI)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Fork rebound
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.ForkRebound)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Shock PSI
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.ShockPSI)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Shock Rebound
                        </td>
                        <td>
                                        @Html.DisplayFor(model => model.ShockRebound)
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col">
            <img class="rounded img-fluid" src="@($"/Bikes/Images/{Model.Id}.jpg")" >
        </div>
    </div>
</div>
<br />
<br />

<div class="row">
    <div class="d-grid gap-2 col-6 mx-auto">
        <a asp-controller="Bike" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary"><i class="bi bi-pencil"></i>&nbsp;  Edit</a>
        <a asp-controller="Bike" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-secondary"><i class="bi bi-trash"></i>&nbsp; Delete</a>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

BikeSettings2/Views/Bike/Edit.cshtml
@model Bike
@{
    ViewData["Title"] = "Index";
}

<form enctype="multipart/form-data" method="post"> 
    <div class="border rounded pt-3 mt-4 mx-auto">
        <div class="row pb-2 mx-auto">
            <h3 class="">Edit an existing Bike</h3>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Manufacturer"></label>
            <input asp-for="Manufacturer" class="form-control"/>
            <span asp-validation-for="Manufacturer" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Model"></label>
            <input asp-for="Model" class="form-control"/>
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="FrontTyrePSI"></label>
            <input asp-for="FrontTyrePSI" class="form-control"/>
            <span asp-validation-for="FrontTyrePSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="RearTyrePSI"></label>
            <input asp-for="RearTyrePSI" class="form-control"/>
            <span asp-validation-for="RearTyrePSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ForkPSI"></label>
            <input asp-for="ForkPSI" class="form-control"/>
            <span asp-validation-for="ForkPSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ForkRebound"></label>
            <input asp-for="ForkRebound" class="form-control"/>
            <span asp-validation-for="ForkRebound" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ShockPSI"></label>
            <input asp-for="ShockPSI" class="form-control"/>
            <span asp-validation-for="ShockPSI" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="ShockRebound"></label>
            <input asp-for="ShockRebound" class="form-control"/>
            <span asp-validation-for="ShockRebound" class="text-danger"></span>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <label asp-for="Image"></label>
            <input asp-for="Image" type="file"/>
        </div>
        <div class="mb-3 px-2 mx-auto">
            <button type="submit" class="btn btn-primary"> <i class="bi bi-bicycle"></i> &nbsp; Save changes</button>
            <a asp-controller="Bike" asp-action="Index" method="post" class="btn btn-secondary">Back to List</a> 
        </div>

    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

BikeSettings2/Views/Bike/Index.cshtml
@model IEnumerable<Bike>
@{
    ViewData["Title"] = "Index";
}


 <div class="container p-3">
     <div class="row pt-4">
         <div class="col-6 text-lg-start align-text-top">
             <h2>Bike List</h2>
         </div>
         <div class="col-6 text-end align-text-bottom">
             <a asp-controller="Bike" asp-action="Create" class="btn btn-primary"><i class="bi bi-bicycle"></i> &nbsp; Create new Bike</a>
         </div> 
         <hr />
     </div>
     <br />
         
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Manufacturer
                </th>
                <th>
                    Model
                </th>
                <th>
                    Front Tyre PSI
                </th>
                <th>
                    Rear Tyre PSI
                </th>
                <th>
                    Fork PSI
                </th>
                <th>
                    Fork Rebound
                </th>
                <th>
                   Shock PSI
                </th>
                <th>
                    Shock Rebound
                </th>
                <th>

                </th>
                <th>

                </th>
                <th>

                </th>
                <th>
                    Image
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>
                        @obj.Manufacturer
                    </td>
                    <td>
                        @obj.Model
                    </td>
                    <td>
                        @obj.FrontTyrePSI
                    </td>
                    <td>
                        @obj.RearTyrePSI
                    </td>
                    <td>
                        @obj.ForkPSI
                    </td>
                    <td>
                        @obj.ForkRebound
                    </td>
                    <td>
                        @obj.ShockPSI
                    </td>
                    <td>
                        @obj.ShockRebound
                    </td>
                    <td>
                        <a asp-controller="Bike" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary"><i class="bi bi-pencil"></i>&nbsp;  Edit</a>
                    </td>
                    <td>
                        <a asp-controller="Bike" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-secondary"><i class="bi bi-trash"></i>&nbsp; Delete</a>
                    </td>
                    <td>
                        <a asp-controller="Bike" asp-action="Details" asp-route-id="@obj.Id" class="btn btn-secondary"><i class="bi bi-info-circle"></i>&nbsp; Details</a>
                    </td>
                    <td>
                                    <img class="rounded" src="@($"/Bikes/Images/{obj.Id}.jpg")" width="50" height="52">
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

BikeSettings2/Views/Bike/Search.cshtml
@model IEnumerable<Bike>
@{
    ViewData["Title"] = "Index";
}
<br />
<h2>Search for a Bike</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary mt-2">Back to List</a>
</div>